Server.initialized: true
Server.fleetspeak_enabled: true
Server.fleetspeak_server: fleetspeak-admin:4444
Server.fleetspeak_message_listen_address: grr-fleetspeak-frontend:11111

AdminUI.csrf_secret_key: random_passphrase____PLEASE_REPLACE_WHEN_RUNNING_IN_PRODUCTION____
AdminUI.url: http://admin-ui:8000
AdminUI.bind: 0.0.0.0
AdminUI.use_precompiled_js: true

API.DefaultRouter: ApiCallRouterWithoutChecks

Mysql.host: grr.cf0ygy60ymd2.ap-south-1.rds.amazonaws.com
Mysql.port: 7272
Mysql.database_name: fleetspeak
Mysql.database_password: IDzgVabzEj5i8oFyOPtv
Mysql.database_username: grradmin
Mysql.database: grr
Mysql.password: IDzgVabzEj5i8oFyOPtv
Mysql.username: grradmin

Blobstore.implementation: DbBlobStore
Database.implementation: MysqlDB

Client.executable_signing_public_key: "%(/configs/public-key.pem|file)"
PrivateKeys.executable_signing_private_key: "%(/configs/private-key.pem|file)"

# Configuration for repacking client templates:
Client.fleetspeak_enabled: true
ClientBuilder.fleetspeak_bundled: true
ClientBuilder.template_dir: /client_templates
ClientBuilder.executables_dir: /client_installers

Target:Linux:
  ClientBuilder.fleetspeak_client_config: /configs/client/client.config
Target:Windows:
  ClientBuilder.fleetspeak_client_config: /configs/client/client.config
Target:Darwin:
  ClientBuilder.fleetspeak_client_config: /configs/client/client.config
